import "@/styles/globals.css";
import { type Metadata } from "next";
import { SessionProvider } from 'next-auth/react'
import { auth } from '@/auth'
import { Toaster } from "@/components/ui/sonner";
import { Poppins } from "next/font/google";

const poppins = Poppins({ weight: "500", style: "normal", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Find Your Tutor",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <head>
          <meta charSet="UTF-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        </head>
        <body className={`${poppins.className} flex flex-col`}>
          <Toaster position='top-center' richColors />
          {children}
        </body>
      </html>
    </SessionProvider>
  );
}
